version: '3.8'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile_app
    container_name: laravelProject-app
    volumes:
      - ./app:/var/www/app
    networks:
      sample-network:
        aliases:
          - app.sample.jp

  nginx:
    image: nginx:latest
    container_name: laravelProject-nginx
    ports:
      - 8080:80 
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      sample-network:
  
  db:
    build:
      context: ./docker
      dockerfile: Dockerfile_db
    image: mysql:latest
    container_name: laravelProject-db
    platform: linux/x86_64
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - $HOME/var/lib/mysql:/var/lib/mysql
    networks:
      sample-network:

networks:
  sample-network:
    driver: bridge
    internal: false
    name: sample-network