FROM php:8.0-fpm 
COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer
RUN apt update &&\
    curl -sL https://deb.nodesource.com/setup_19.x | bash - &&\
    apt install -y less git zip unzip nodejs &&\
    docker-php-ext-install pdo_mysql
WORKDIR "/var/www/app"